<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>true</IsPackable>
		<Description>Defines the core domain entities and value objects for the Ground framework.</Description>
		<PackageTags>Domain;Entities;ValueObjects;Ground</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\1.Utilities\Ground.Utilities\Ground.Utilities.csproj" />
	</ItemGroup>

</Project>
