<Project>
  <PropertyGroup>
    <Authors>Abbas Vosoughi</Authors>
    <PackageProjectUrl>https://github.com/vosooghi/Ground</PackageProjectUrl>
    <RepositoryUrl>https://github.com/vosooghi/Ground</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <PackageIcon>Icon.png</PackageIcon>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
