<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>true</IsPackable>
		<Description>Translation extensions for Ground framework</Description>
		<PackageTags>translations;ground;extensions</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Dapper" Version="2.1.66" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.1" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Ground.Extensions.Abstractions\Ground.Extensions.Translations.Abstractions\Ground.Extensions.Translations.Abstractions.csproj" />
	</ItemGroup>

</Project>
