<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>true</IsPackable>
	</PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\1.Utilities\Ground.Utilities\Ground.Utilities.csproj" />
    <ProjectReference Include="..\Ground.Core.Domain\Ground.Core.Domain.csproj" />
    <ProjectReference Include="..\Ground.Core.RequestResponse\Ground.Core.RequestResponse.csproj" />
  </ItemGroup>

</Project>
