<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>true</IsPackable>
		<Description>Provides abstractions for event mechanisms. Interfaces and classes defined in this package are used in Ground microservice framework.</Description>
		<PackageTags>ground events abstractions</PackageTags>
	</PropertyGroup>
</Project>
