@Ground.Utilities.Authentication.ApiAuthentication.Sample_HostAddress = http://localhost:5030

GET {{Ground.Utilities.Authentication.ApiAuthentication.Sample_HostAddress}}/weatherforecast/
Accept: application/json

###
