<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>true</IsPackable>
		<Description>Provides AutoMapper integration for the Ground.Extensions.ObjectMappers library.</Description>
		<PackageTags>AutoMapper, Ground.Extensions.ObjectMappers, Adapter</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="16.1.1" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.5" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
		<PackageReference Include="Microsoft.Extensions.DependencyModel" Version="10.0.5" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.5" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.5" />
		<PackageReference Include="System.Reflection" Version="4.3.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Ground.Extensions.Abstractions\Ground.Extensions.ObjectMappers.Abstractions\Ground.Extensions.ObjectMappers.Abstractions.csproj" />
	</ItemGroup>

</Project>
