<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<isPackable>false</isPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.5" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Extensions\UserManagement\Ground.Extensions.UsersManagement\Ground.Extensions.UsersManagement\Ground.Extensions.UsersManagement.csproj" />
		<ProjectReference Include="..\Ground.Utilities.SerilogRegistration\Ground.Utilities.SerilogRegistration.csproj" />
	</ItemGroup>

</Project>
